# Generated by Django 5.0.2 on 2024-03-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_date", models.DateField()),
                ("event_name", models.CharField(max_length=200)),
                ("event_description", models.TextField()),
                ("tags", models.CharField(max_length=200)),
                ("link_to_info", models.URLField()),
            ],
        ),
    ]
