# Generated by Django 5.0.2 on 2024-03-08 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="event_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="event",
            old_name="event_name",
            new_name="name",
        ),
    ]
